### PR TITLE
Add AC(All Clear) and Del buttons

### PR DESCRIPTION
**Pull request by CarsonChen1129**
- Add AC(All Clear) button and Del button, use ACDelbuttons:true to able these buttons (Default is false since it is an option). 

- Create individual css class for these buttons in case someone wants to customize these buttons. Use [buttonACTextColor, buttonACColor] for button AC and use [buttonDelTextColor, buttonDelColor] for button Del

- Update the README description

### CODE REVIEW

**Comment by AlexDisler** [comment]
Thanks for the pull request!

I see you made the changes on the file in the dist folder. This file should be generated by gulp and not modified manually.

Can you please make these changes on the [source file](https://github.com/AlexDisler/ionic-lock-screen/blob/master/src/lock-screen/lock-screen.js) instead?

you can then run:

    gulp build

and it will generate the minified distribution file.

**Comment by CarsonChen1129** [comment]
Sure, this is just a draft pull request, I will build it via gulp and make another pull request if you think my modifications are acceptable.

**Comment by AlexDisler** [comment]
yeah looks good, thanks

**Comment by CarsonChen1129** [comment]
Generated the minified distribution file and updated the devDependencies.

**Pull request merged**
